//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int ID { get; set; }
        public string IDName { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
